version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"

